package homebrew

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const (
	repoURL = "https://github.com/dannyneumann/md2c"
	license = "MIT"
)

type artifact struct {
	Name string
	SHA  string
	URL  string
}

var platforms = []struct {
	goos, goarch string
}{
	{"darwin", "amd64"},
	{"darwin", "arm64"},
	{"linux", "amd64"},
	{"linux", "arm64"},
}

// NormalizeVersion strips a leading v, e.g. v0.2.2 → 0.2.2.
func NormalizeVersion(version string) string {
	return strings.TrimPrefix(strings.TrimSpace(version), "v")
}

func artifactName(version, goos, goarch string) string {
	return fmt.Sprintf("md2c_v%s_%s_%s", version, goos, goarch)
}

func releaseURL(version, name string) string {
	return fmt.Sprintf("%s/releases/download/v%s/%s", repoURL, version, name)
}

// ParseSHA256SUMS reads `sha256sum` output (HASH  FILE) into a name→digest map.
func ParseSHA256SUMS(r io.Reader) (map[string]string, error) {
	out := make(map[string]string)
	sc := bufio.NewScanner(r)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			return nil, fmt.Errorf("SHA256SUMS line %d: want HASH FILE", lineNo)
		}
		sum := strings.ToLower(fields[0])
		name := strings.TrimPrefix(fields[len(fields)-1], "*")
		if len(sum) != 64 || strings.IndexFunc(sum, func(r rune) bool {
			return !unicode.Is(unicode.ASCII_Hex_Digit, r)
		}) >= 0 {
			return nil, fmt.Errorf("SHA256SUMS line %d: invalid sha256", lineNo)
		}
		out[name] = sum
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("SHA256SUMS: no checksums")
	}
	return out, nil
}

func artifacts(version string, sums map[string]string) (map[string]artifact, error) {
	v := NormalizeVersion(version)
	if v == "" {
		return nil, fmt.Errorf("version is empty")
	}
	out := make(map[string]artifact, len(platforms))
	for _, p := range platforms {
		name := artifactName(v, p.goos, p.goarch)
		sha, ok := sums[name]
		if !ok {
			return nil, fmt.Errorf("missing sha256 for %s", name)
		}
		key := p.goos + "/" + p.goarch
		out[key] = artifact{Name: name, SHA: sha, URL: releaseURL(v, name)}
	}
	return out, nil
}

func platformBlock(cpu string, a artifact) string {
	return fmt.Sprintf(`    on_%s do
      url "%s", using: :nounzip
      sha256 "%s"

      def install
        bin.install "%s" => "md2c"
      end
    end
`, cpu, a.URL, a.SHA, a.Name)
}

// Generate returns a Homebrew formula for the GitHub release binaries.
func Generate(version string, sums map[string]string) (string, error) {
	v := NormalizeVersion(version)
	arts, err := artifacts(v, sums)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# typed: false\n")
	b.WriteString("# frozen_string_literal: true\n\n")
	b.WriteString("# Generated by cmd/update-homebrew-formula. Do not edit.\n")
	b.WriteString("class Md2c < Formula\n")
	b.WriteString("  desc \"Publish Markdown files to Confluence\"\n")
	fmt.Fprintf(&b, "  homepage \"%s\"\n", repoURL)
	fmt.Fprintf(&b, "  version \"%s\"\n", v)
	fmt.Fprintf(&b, "  license \"%s\"\n\n", license)
	b.WriteString("  livecheck do\n")
	b.WriteString("    url :homepage\n")
	b.WriteString("    strategy :github_latest\n")
	b.WriteString("  end\n\n")
	b.WriteString("  on_macos do\n")
	b.WriteString(platformBlock("intel", arts["darwin/amd64"]))
	b.WriteString(platformBlock("arm", arts["darwin/arm64"]))
	b.WriteString("  end\n\n")
	b.WriteString("  on_linux do\n")
	b.WriteString(platformBlock("intel", arts["linux/amd64"]))
	b.WriteString(platformBlock("arm", arts["linux/arm64"]))
	b.WriteString("  end\n\n")
	b.WriteString("  test do\n")
	b.WriteString("    assert_match(/^md2c v/, shell_output(\"#{bin}/md2c -version\"))\n")
	b.WriteString("  end\n")
	b.WriteString("end\n")
	return b.String(), nil
}

// WriteFormula writes Generate() to path, creating parent directories.
func WriteFormula(path, version string, sums map[string]string) error {
	body, err := Generate(version, sums)
	if err != nil {
		return err
	}
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(path, []byte(body), 0o644)
}
