# typed: false
# frozen_string_literal: true

# Generated by cmd/update-homebrew-formula. Do not edit.
class Md2c < Formula
  desc "Publish Markdown files to Confluence"
  homepage "https://github.com/dannyneumann/md2c"
  version "0.2.4"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.4/md2c_v0.2.4_darwin_amd64", using: :nounzip
      sha256 "99a40dd74f89bbe7b8fd6a1b4f135722587daabd0911dd6ec0f9caa8f584b57d"

      def install
        bin.install "md2c_v0.2.4_darwin_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.4/md2c_v0.2.4_darwin_arm64", using: :nounzip
      sha256 "8628294715f9aab7113d8c503e9b734cee9de3f1680d31391852d33fabef83ec"

      def install
        bin.install "md2c_v0.2.4_darwin_arm64" => "md2c"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.4/md2c_v0.2.4_linux_amd64", using: :nounzip
      sha256 "2f9ba8393a4fd695d6e0ab5eaa1dcca057bac8f12f783f3c17227b1868719ffa"

      def install
        bin.install "md2c_v0.2.4_linux_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.4/md2c_v0.2.4_linux_arm64", using: :nounzip
      sha256 "ae19999f85cda2f8677124171154e1121ed4f443549413b1adfb276048b74d0f"

      def install
        bin.install "md2c_v0.2.4_linux_arm64" => "md2c"
      end
    end
  end

  test do
    assert_match(/^md2c v/, shell_output("#{bin}/md2c -version"))
  end
end
