# typed: false
# frozen_string_literal: true

# Generated by cmd/update-homebrew-formula. Do not edit.
class Md2c < Formula
  desc "Publish Markdown files to Confluence"
  homepage "https://github.com/dannyneumann/md2c"
  version "0.2.21"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.21/md2c_v0.2.21_darwin_amd64", using: :nounzip
      sha256 "f8ce25d7806ce369b12f72fdb8d87de49c8606d12d0fc265aab7284e400cfa6b"

      def install
        bin.install "md2c_v0.2.21_darwin_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.21/md2c_v0.2.21_darwin_arm64", using: :nounzip
      sha256 "309314b37dbd144bced9bed10a9522b8f2ebb86942d1ebc8eca89e5ec21856bf"

      def install
        bin.install "md2c_v0.2.21_darwin_arm64" => "md2c"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.21/md2c_v0.2.21_linux_amd64", using: :nounzip
      sha256 "5ec3737415041e6d1a38591f9d3577c9f3a5e7d7bf553b3b954d245b58e36ae9"

      def install
        bin.install "md2c_v0.2.21_linux_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.2.21/md2c_v0.2.21_linux_arm64", using: :nounzip
      sha256 "2d1c77c1eb14636e5e043cb3be6dc049b60fd909206517fcb40f563ef2b84fe6"

      def install
        bin.install "md2c_v0.2.21_linux_arm64" => "md2c"
      end
    end
  end

  test do
    assert_match(/^md2c v/, shell_output("#{bin}/md2c -version"))
  end
end
