# typed: false
# frozen_string_literal: true

# Generated by cmd/update-homebrew-formula. Do not edit.
class Md2c < Formula
  desc "Publish Markdown files to Confluence"
  homepage "https://github.com/dannyneumann/md2c"
  version "0.1.0"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  on_macos do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.1.0/md2c_v0.1.0_darwin_amd64", using: :nounzip
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

      def install
        bin.install "md2c_v0.1.0_darwin_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.1.0/md2c_v0.1.0_darwin_arm64", using: :nounzip
      sha256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"

      def install
        bin.install "md2c_v0.1.0_darwin_arm64" => "md2c"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.1.0/md2c_v0.1.0_linux_amd64", using: :nounzip
      sha256 "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"

      def install
        bin.install "md2c_v0.1.0_linux_amd64" => "md2c"
      end
    end
    on_arm do
      url "https://github.com/dannyneumann/md2c/releases/download/v0.1.0/md2c_v0.1.0_linux_arm64", using: :nounzip
      sha256 "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"

      def install
        bin.install "md2c_v0.1.0_linux_arm64" => "md2c"
      end
    end
  end

  test do
    assert_match(/^md2c v/, shell_output("#{bin}/md2c -version"))
  end
end
